package Java15;

public class WorkWithStringConst {
    // previous string const. Hurt with SQL)
    private static final String previousString = "HELLLO LONG STRING BRO HELLLO LONG STRING BRO HELLLO LONG STRING BRO" +
            "HELLLO LONG STRING BRO HELLLO LONG STRING BRO HELLLO LONG STRING BRO HELLLO LONG STRING BRO" +
            "HELLLO LONG STRING BRO HELLLO LONG STRING BRO";

    // But now we can use string literal triable
    private static final String newString = """
    HELLLO LONG STRING BRO HELLLOHELLLO
    LONG STRING BRO HELLLO 
    HELLLO LONG STRING BRO HELLLOHELLLO LONG STRING BRO HELLLOHELLLO LONG STRING BRO HELLLO
    HELLLO LONG STRING BRO HELLLOHELLLO LONG STRING BRO HELLLOHELLLO LONG STRING BRO HELLLO
    """;

    public static void main(String[] args) {
        System.out.println(previousString);
        System.out.println("\n" + newString);
    }

    // output
//    HELLLO LONG STRING BRO HELLLO LONG STRING BRO HELLLO LONG STRING BROHELLLO LONG STRING BRO HELLLO LONG STRING BRO HELLLO LONG STRING BRO HELLLO LONG STRING BROHELLLO LONG STRING BRO HELLLO LONG STRING BRO
//
//    HELLLO LONG STRING BRO HELLLOHELLLO
//    LONG STRING BRO HELLLO
//    HELLLO LONG STRING BRO HELLLOHELLLO LONG STRING BRO HELLLOHELLLO LONG STRING BRO HELLLO
//    HELLLO LONG STRING BRO HELLLOHELLLO LONG STRING BRO HELLLOHELLLO LONG STRING BRO HELLLO
}
